nyc_yellow_taxi_dwh:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"   
      user: dbt_user
      password: dbt_password
      dbname: dwh_db
      port: 5434       # mapped host port (host:container = 5434:5432 in docker-compose)
      schema: public
      threads: 4