version: 2

models:
  # TABLE DE FAITS (GOLD)
  - name: fact_taxi_trips_v2
    description: "table de faits des trajets de taxi jaune à NYC"
    columns:
      - name: trip_key
        description: "Surrogate Key unique"
        tests:
          - unique
          - not_null

      - name: pickup_date_id
        description: "Clé FK vers Dim_Date"
        tests:
          - not_null
          - relationships: 
              to: ref('dim_date')
              field: date_id

      - name: pickup_time_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_time')
              field: time_id

      - name: total_amount
        description: "Montant total calculé (Source of Truth)"
        tests:
          - not_null
          - dbt_utils.expression_is_true:
              expression: ">= 0" 

      - name: passenger_count
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: trip_distance
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

    # TESTS DE TABLE 
    tests:
      # 1. Cohérence Temporelle : Dropoff doit être après Pickup
      - dbt_utils.expression_is_true:
          expression: "dropoff_date_id > pickup_date_id OR (dropoff_date_id = pickup_date_id AND dropoff_time_id >= pickup_time_id)"
          name: check_dropoff_after_pickup

      # 2. Cohérence Financière : Le Total doit être égal à la somme des composants
      # On tolère une marge d'erreur de 0.02$ pour les arrondis flottants
      - dbt_utils.expression_is_true:
          expression: "abs(total_amount - (base_fare_usd + surcharges_usd + mta_tax_usd + tip_amount_usd + tolls_amount_usd + improvement_surcharge + congestion_surcharge + airport_fee)) <= 0.02"
          name: check_financial_consistency

  # DATA MARTS (VUES AGRÉGÉES)
  - name: agg_borough_analysis
    description: "Analyse géographique par quartier"
    columns:
      - name: total_revenue_usd
        tests:
          - dbt_utils.expression_is_true:
              expression: ">= 0"

      - name: avg_fare_usd
        tests:
          # Warning si le panier moyen dépasse 500$ (anomalie statistique potentielle)
          - dbt_utils.expression_is_true:
              expression: "< 500" 
              config:
                severity: warn # ne bloque pas l'éxécution de gad, mais donne un avertissement

  - name: agg_payment_analysis
    description: "Analyse des paiements et parts de marché"
    columns:
      - name: payment_method_share_pct
        tests:
          # Le pourcentage doit être mathématiquement valide (0-100)
          - dbt_utils.expression_is_true:
              expression: "BETWEEN 0 AND 100"

# expression_is_true
  #C’est un test DBT qui vérifie qu’une expression SQL est vraie pour chaque ligne du modèle.
  #Si l’expression est FAUSSE pour au moins une ligne → le test échoue.